### ISSUE TITLE
Add GraphRegressor task

### ISSUE THREAD

**Issue by Irlirion** [Lightning-AI/lightning-flash#1407] opened 2022-07-28 13:33 UTC
## 🚀 Feature
Add the graph regression task support

### Motivation

I have been working on graph neural networks for some time now. I want to use lightning flash for a graph regression task, but have only found an implementation for classification, which is a ted disappointing.

### Pitch

Scientists are not limited to the task of graph classification, we also need a quick way to solve our problems using lightning flash. Adding a regression task doesn't look very difficult. I already have a working version, which I will publish in PR later.

**Comment by krshrimali** [comment] 2022-08-22 06:14
Hi, @Irlirion - Apologies for the delay in response. Thank you for the feature request. I think it will be worth adding, and since you mentioned that you already have a working version, would you mind creating a PR whenever you get the time? I would love to have it for v0.8 if we can get the PR merged in the next 2 weeks, but of course - it depends on how much bandwidth you have. In case you don't have the time, please feel free to create a draft PR with whatever changes you have, and I can take it from there to furnish it and add required tests to get it there!

**Comment by uakarsh** [comment] 2022-09-07 18:45
Hi @Irlirion, are you still working on this PR? I would be happy to help you add a graph regression task in Flash.

**Closed** 2023-03-19 16:08 UTC
Labels: enhancement, help wanted, won't fix
